USE [master]
GO

CREATE DATABASE [ServerTrace_DW]
GO

USE [master]
GO
ALTER DATABASE [ServerTrace_DW] MODIFY FILE ( NAME = N'ServerTrace_DW', SIZE = 512000KB , FILEGROWTH = 512000KB )
GO
ALTER DATABASE [ServerTrace_DW] MODIFY FILE ( NAME = N'ServerTrace_DW_log', SIZE = 256000KB, FILEGROWTH = 256000KB)
GO
