USE [master]
GO

CREATE DATABASE [inbound]
GO


USE [master]
GO
ALTER DATABASE [inbound] MODIFY FILE ( NAME = N'inbound', SIZE = 102400KB , FILEGROWTH = 102400KB )
GO
ALTER DATABASE [inbound] MODIFY FILE ( NAME = N'inbound_log', SIZE = 102400KB , FILEGROWTH = 102400KB )
GO
